### ISSUE TITLE
Investigate the possibility of adding a dependency on the ocaml-sys crate to avoid duplication

### ISSUE THREAD

**Issue by tizoc** [simplestaking/ocaml-interop#7]
There is some duplication between the core of this library and `ocaml-sys`. If there are no incompatibilities, using `ocaml-sys` may be a better alternative than keeping a duplicate implementation here.

**Comment by tizoc** [comment]
PR here https://github.com/simplestaking/ocaml-interop/pull/12

**Comment by tizoc** [comment]
Solved by #12

**Comment by tizoc** [comment]
@zshipko this is in. There is something stuff I have to work on (unrelated to ocaml-interop), but before switching to that other task I will go through both codebases and try to lay out a (probably mostly high level) plan detailing what should be done to sandwich ocaml-interop between ocaml-rs and ocaml-sys and open a new issue so that I can get your input/comments. That will provide us with some good ground for when we have a meeting with everybody else next week.

**Comment by zshipko** [comment]
Awesome, sounds good!
